### ISSUE TITLE
Deprecate `adlfs.*` configuration properties in favor of `adls.*`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#866] opened 2024-06-28 09:43 UTC
### Feature Request / Improvement

To set up a configuration to ADLS, we use now `adlfs.*` prefixed properties. This is refers to the implementation, and we want to use `adls`. See https://py.iceberg.apache.org/configuration/

What we want to do:

- Replace `adlfs` to `adls`, and emit a warning when we see this to let the user know that aldfs is being deprecated.
- Update the properties and docs with `adls`.

**Comment by ndrluis** [comment] 2024-07-04 13:26
Hello @Fokko,

I'd like to resolve this issue. I just want to confirm the expected behavior. Since we are replacing ADLFS with ADLS, I believe the expected behavior should be to raise an error. If we choose to warn instead, it means we are not replacing ADLFS but supporting both, and we are implying that we will eventually stop supporting the ADLFS prefix.

What should the expected behavior be?

**Comment by kevinjqliu** [comment] 2024-11-15 00:07
closed by #961

**Closed by kevinjqliu** 2024-11-15 00:07 UTC
Labels: good first issue
