### ISSUE TITLE
support partition spec update in pyiceberg

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg-python#124] opened 2023-11-02 21:02 UTC
### Feature Request / Improvement

as title.

**Comment by Fokko** [comment] 2023-11-06 09:10
Thanks for raising this! @puchengy which catalog are you using? 

Related is https://github.com/apache/iceberg-python/issues/22

**Comment by syun64** [comment] 2024-02-07 01:50
Duplicate of https://github.com/apache/iceberg-python/issues/193

**Closed by syun64** 2024-02-07 01:50 UTC
