### ISSUE TITLE
Cannot create table if location/endpoint is s3 on a "secure" Minio server

### ISSUE THREAD

**Issue by thinkORo** [apache/iceberg-python#540] opened 2024-03-21 19:17 UTC
### Apache Iceberg version

0.6.0 (latest release)

### Please describe the bug 🐞

I've create a .pyiceberg.yaml file with the following content:

```
catalog:
  default:
    s3.endpoint: https://localhost:9199
    s3.access-key-id: iceberg
    s3.secret-access-key: iceberg123
    s3.region: us-east-1
    type: sql
    uri: postgresql+psycopg2://iceberg:iceberg123@localhost:5432/iceberg
```

My code is like this:

```
from pyiceberg.catalog import load_catalog
import pyarrow.parquet as pq

catalog = load_catalog('default')
df = pq.read_table("yellow_tripdata_2023-01.parquet")

catalog.create_namespace("demo")
table = catalog.create_table(
    "demo.taxi_dataset",
    schema=df.schema,
    location="s3://iceberg",
)
```
If I'd change the location from s3 to any location on my local drive (like: /tmp/iceberg) everything works fine. But with S3 I'd get the following error:

```
OSError: When getting information for key 'metadata/00000-97670b6c-f2c1-45a0-8026-b47087f28abe.metadata.json' in bucket 'iceberg': AWS Error NETWORK_CONNECTION during HeadObject operation: curlCode: 60, SSL peer certificate or SSH remote key was not OK
```

I didn't find any solution to handle this issue. Could one please give me some advices?

**Comment by thinkORo** [comment] 2024-03-22 06:47
I double-checked my configuration with a second tool, duckDB. With duckDB I can access the data in minio with the same credentials without any problems.

These are my corresponding duckDB connection settings:
```
conn.execute("SET s3_region='us-east-1'")
conn.execute("SET s3_endpoint='localhost:9199'")
conn.execute("SET s3_use_ssl=true")
conn.execute("SET s3_url_style='path'")
conn.execute("SET s3_access_key_id='iceberg'")
conn.execute("SET s3_secret_access_key='iceberg123'")
```
From my perspective: There is something missing in the S3FileSystem in pyarrow. Am I wrong?

**Comment by kevinjqliu** [comment] 2024-03-24 17:39
I think this is an issue with the s3 endpoint. Specifically with using https, `https://localhost:9199`. We're using `http` instead of `https` in the integration test
https://github.com/apache/iceberg-python/blob/6989b92c2d449beb9fe4817c64f619ea5bfc81dc/dev/provision.py#L33

The problem goes away for me after using `http://`
Can you give that a try?

**Comment by kevinjqliu** [comment] 2024-03-24 17:41
If you must use `https`, maybe there's an issue with the way Minio is set up 
https://stackoverflow.com/questions/66161424/minio-does-not-seem-to-recognize-tls-https-certificates

**Comment by kevinjqliu** [comment] 2024-03-24 17:43
https://github.com/fsspec/s3fs/issues/342

might be relevant

**Comment by kevinjqliu** [comment] 2024-03-24 18:00
It looks like PyArrow is looking for the cert here
https://github.com/apache/arrow/blob/6aa6f859bf1aee7cea65e8ab8a85fe6c0119a0ae/python/pyarrow/_fs.pyx#L36-L45

https://github.com/minio/minio/issues/12569#issuecomment-867879716

Hope this helps!

**Comment by thinkORo** [comment] 2024-03-25 09:32
Hi Kevin,

thank you for your hints.

I think the main problem is that the implementation of pyarrow for S3FileSystem is different from that of s3fs.

With s3fs there are more possibilities to influence the runtime behavior.

But your hint about "_fs.pyx" (https://github.com/apache/arrow/blob/6aa6f859bf1aee7cea65e8ab8a85fe6c0119a0ae/python/pyarrow/_fs.pyx#L36-L45) has led to a solution for me. Thank you very much.

What have I done now? When I look at the values for "ssl.get_default_verify_paths()", I see the corresponding pem file in which the CAs are stored. I have added my CA to this pem file (in my case: ./envs/iceberg/ssl/cert.pem). And now it works.

I am very happy about your hint. Thank you very much!

**Comment by thinkORo** [comment] 2024-03-26 05:52
Hi Kevin, should I close this issue? I think everything is documented, isn't it?

Thank you for your support. The only thing that I still need is a data compaction. But I know that someone is working on.
Thank you for developing/support such a great framework.

I'm going to integrate it as soon as possible.

**Comment by kevinjqliu** [comment] 2024-03-26 15:54
We can close this out. The issue is between pyiceberg and minio integration over HTTPS. We don't have a place to document minio specific behavior.

**Closed** 2024-03-26 17:52 UTC

**Comment by MongoExpUser** [comment] 2024-05-30 08:10
@thinkORo ,

**I was having the same issue. The following snippets solved the problem:**

```
catalog:
    default:
       "s3.endpoint": f"https://s3.{region_name}.amazonaws.com"
       "s3.access-key-id":  f"{my_key_id}
       "s3.secret-access-key":  f"{my_secret_key}
       "s3.region": f"{region_name}"
       "type": "sql"
      "uri": "postgresql+psycopg2://dbuser:dbpassword@server_ip_or_uri:5432/dbname",
      "py-io-impl": "pyiceberg.io.pyarrow.PyArrowFileIO"

catalog.create_namespace("demo")
table = catalog.create_table(
    "demo.taxi_dataset",
    schema=df.schema,
    location=f"s3://{bucket_name}"
)
```
